- name: Elasticsearch configuration
  template: 
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root
    group=elasticsearch
    mode=0644

- name: Debugging docker
  shell: ls -lat /etc/init.d/
  register: ls_command

- name: Show debug
  debug: var=ls_command

- name: Enable elasticsearch service
  service:
    name=elasticsearch
    enabled=yes
    state=started
